<?php
/** @var \ReactEdge\WidgetBridge\Block\Widget $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \ReactEdge\WidgetBridge\ViewModel\Widget $viewModel */

$viewModel = $block->getViewModel();
$widgetId = $block->getData('widget_id');

if (!$viewModel->isEnabled($widgetId)) {
    return;
}

?>

<nav class="navigation" data-action="navigation">
    <div data-reactedge-instance>
        <?= $viewModel->getWidgetSSRHtml($widgetId); ?>
        <megamenu-widget data-load="eager" hidden></megamenu-widget>
    </div>
</nav>
