<?php
/** @var \ReactEdge\WidgetBridge\Block\Widget $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \ReactEdge\WidgetBridge\ViewModel\Widget $viewModel */

$viewModel = $block->getViewModel();
$widgetId = $block->getData('widget_id');

if (!$viewModel->isEnabled($widgetId)) {
    return;
}
?>

<div data-reactedge-instance>
    <?= $viewModel->getWidgetSSRHtml($widgetId); ?>
    <productgallery-widget data-load="eager" style="opacity: 0"></productgallery-widget>
</div>
