<?php
/** @var \ReactEdge\WidgetBridge\Block\Widget $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \ReactEdge\WidgetBridge\ViewModel\Widget $viewModel */

$viewModel = $block->getViewModel();
?>

<script type="application/json" id="reactedge-registry">
  <?= json_encode($viewModel->getRuntimeRegistry()) ?>
</script>

<script type="application/json" id="reactedge-runtime">
  <?= $viewModel->getRuntimeConfig(); ?>
</script>

<script type="application/json" id="reactedge-observability">
  <?= $viewModel->getObservabilityContext(); ?>
</script>
